spring.application.name=juegos

# MySQL local
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/playresdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#JWT
jwt.secret=${JWT_SECRET:playres-secret-key-cambia-esto-en-produccion-2024}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

#Credenciales de administrador
admin.email=${ADMIN_EMAIL:admin@playres.com}
admin.password=${ADMIN_PASSWORD:Admin123!}  

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
